### ISSUE TITLE
How can we see if the app has alteady the permissions, before show a mesage with why we are asking for them?

### ISSUE THREAD

**Issue by jrcacd** [Fondesa/KPermissions#21]

**Comment by Fondesa** [comment]
If the app has already the permissions, you will receive a "permissions accepted" callback.
The message used to show the explanation for the permissions' usage must be shown inside the "permissions should show rationale" callback.

So, in your case, you can do something like that (for this example I'll use the inline listeners):
```kotlin
request.onAccepted { permissions -> 
        // The user accepted the permissions or the permissions are already accepted,
        // handle the action.
    }.onShouldShowRationale { permissions, nonce -> 
        // Show the message with the explanation of why you are asking for them. 
    }
```

**Comment by jrcacd** [comment]
Ok, thanks.

**Comment by Chullian** [comment]
`request.onAccepted { permissions -> 
 // The user accepted the permissions or the permissions are already accepted,
        // handle the `action.`
}`

is not being called if the permission is granted already
