### ISSUE TITLE
Attaching listeners via DSL is not working

### ISSUE THREAD

**Issue by ogasimli** [Fondesa/KPermissions#23]
**KPermissions version**: 1.0.0

**Android version**: 7.1.2

**Android device**: OnePlus One

**How to reproduce it**:  I have used dsl listeners on sample app provided by you. I am not getting any error. Just nothing happens when I click the button.

**Block of code**:

```kotlin
class MainActivity : AppCompatActivity() {

    private val request by lazy {
        permissionsBuilder(Manifest.permission.CAMERA)
                .build()
    }

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        setupPermissionRequestListeners()

        findViewById<View>(R.id.btn_test_activity_permissions).setOnClickListener {
            request.send()
        }

        supportFragmentManager.beginTransaction()
                .add(R.id.fragment_container, DummyFragment())
                .commit()
    }

    private fun setupPermissionRequestListeners() {
        request.listeners {

            onAccepted { permissions ->
                // Notified when the permissions are accepted.
                toastOf(R.string.accepted_permissions, permissions)
            }

            onDenied { permissions ->
                // Notified when the permissions are denied.
                toastOf(R.string.denied_permissions, permissions)
            }

            onPermanentlyDenied { permissions ->
                // Notified when the permissions are permanently denied.
                DialogPermanentlyDeniedListener(this@MainActivity)
            }

            onShouldShowRationale { permissions, nonce ->
                // Notified when the permissions should show a rationale.
                // The nonce can be used to request the permissions again.
                DialogRationaleListener(this@MainActivity)
            }
        }
    }

    private fun toastOf(@StringRes format: Int, permissions: Array<out String>) {
        val msg = String.format(getString(format), permissions.flatString())
        Toast.makeText(this, msg, Toast.LENGTH_SHORT).show()
    }
}
```

**Comment by Fondesa** [comment]
I have tested it copying and pasting your block of code on a device with the same Android version.
It behaves correctly.
I can't test it on a OnePlus One so can you answer to the following questions (it will help me to fix this bug)?

- have you experienced this bug on other devices too?
- if you use the in-line or the normal listeners, does it work?
- if you specify other permissions (for example _ACCESS_FINE_LOCATION_), does it work?
- has the device a custom ROM?

**Comment by ogasimli** [comment]
1. Have you experienced this bug on other devices too? - Currently, I don't have any other device to test.
2. If you use the in-line or the normal listeners, does it work? - Yes, everything works good, if I use normal listeners.
3. If you specify other permissions (for example ACCESS_FINE_LOCATION), does it work? - I have also tested with ACCESS_FINE_LOCATION permission, but the result was same.
4. Has the device a custom ROM? - Yes, I am using Lineage OS 14.1

**Comment by Fondesa** [comment]
Can you try to refactor the method `setupPermissionRequestListeners()` in the following way?

```kotlin
private fun setupPermissionRequestListeners() {
    request.onAccepted { permissions ->
            // Notified when the permissions are accepted.
            toastOf(R.string.accepted_permissions, permissions)
        }.onDenied { permissions ->
            // Notified when the permissions are denied.
            toastOf(R.string.denied_permissions, permissions)
        }.onPermanentlyDenied { permissions ->
            // Notified when the permissions are permanently denied.
            DialogPermanentlyDeniedListener(this@MainActivity)
        }.onShouldShowRationale { permissions, nonce ->
            // Notified when the permissions should show a rationale.
            // The nonce can be used to request the permissions again.
            DialogRationaleListener(this@MainActivity)
        }
}
```

Does it work?

**Comment by ogasimli** [comment]
It is very strange because it works only once. That happened when I have used previous code also. I click on a button, permission request pops up, I deny the request and the process is over. After that, I can't get any feedback. It works again only after reinstalling the app.

**Comment by Fondesa** [comment]
Oh, now I understand what is happening. This is the expected behavior with that block of code.
You are using a `RationaleListener` and a `PermanentlyDeniedListener` without invoking anything.
If you want to combine some shared implementation with the DSL, you need to refactor your code like this:

```kotlin
private fun setupPermissionRequestListeners() {
    request.listeners {
        onAccepted { permissions ->
            // Notified when the permissions are accepted.
            toastOf(R.string.accepted_permissions, permissions)
        }
        onDenied { permissions ->
            // Notified when the permissions are denied.
            toastOf(R.string.denied_permissions, permissions)
        }
    }
    request.permanentlyDeniedListener(DialogPermanentlyDeniedListener(this))
    request.rationaleListener(DialogRationaleListener(this))
}
```

The combination of different declarations of listeners is explained [here](https://github.com/Fondesa/KPermissions/wiki/Usage#3-normal-listeners).

**Comment by ogasimli** [comment]
It works now. I have read that section, but didn't understand quite well. My bad. Thank you very much for this awesome library!

**Comment by Fondesa** [comment]
Thanks to you for your support!
