### ISSUE TITLE
Question: How to request different permissions on different actions within one activity?

### ISSUE THREAD

**Issue by ogasimli** [Fondesa/KPermissions#24]
Let's say I want to request ACCES_FINE_LOCATION permission on click to button1, and WRITE_EXTERNAL_STORAGE permission on click to button2. Do I need to declare, attach and detach 2 separate PermissionRequest in order to achieve this?

**Comment by Fondesa** [comment]
Yes, exactly.

The `PermissionRequest` is used to manage the permissions related to a **single** functionality.
If those two actions are related to two different functionalities, you should use two `PermissionRequest` instances. 
If those two actions are related to the same functionalities, you should use one `PermissionRequest` that will request both permissions on both actions.

It was done in this way to make the permissions' request workflow independent from the others.

**Comment by Fondesa** [comment]
@ogasimli Can I close it?

**Comment by ogasimli** [comment]
Yes, Sure! Thanks for the help!
