### ISSUE TITLE
Possible to use it with Service

### ISSUE THREAD

**Issue by wahibhaq** [Fondesa/KPermissions#25]
I haven't decided to use it but would like to ask if its possible to check permission in a foreground service (location service and location permission).

**Comment by Fondesa** [comment]
In a `Service` it's possible only to check if a permission is granted or not.
If you want to display the permission's dialog to change the permission's status, you must use an `Activity` or a `Fragment` because you need an instance of `FragmentManager`.

**Comment by wahibhaq** [comment]
Thanks for responding. I will give it a try.

**Comment by wahibhaq** [comment]
@Fondesa I am finding difficulty initiating it in Service. 

I can't use 

```
    private val request by lazy {
        permissionBuilder(Manifest.permission.CAMERA)
            .build()
    }
```

because it is reporting error `Unresolved reference` because the extension applies on Activity as I can see in `fun Activity.permissionsBuilder(...`

Any comments on a workaround?

**Comment by Fondesa** [comment]
As I said, you can't show the permission's dialog in a `Service`, you can only check if a permission is granted or not with `isPermissionGranted(String)`.
If you want to show the permission's dialog (using a permission builder), you need something which provides an instance of `FragmentManager` (e.g. `Activity`, `Fragment`).

**Comment by wahibhaq** [comment]
I got your point about that but how can I check (or listen for callbacks) in my `Service` if I can't call the `permissionBuilder()` function? I know with Activity it'll work fine but I can't just rely on initialising in Activity because Activity will be killed but Foreground Service will stay.

**Comment by Fondesa** [comment]
You simply can't. It's not a limit of this library, it's a limit of Android SDK. You need an `Activity` or a `Fragment`.
For example you can start an `Activity` from the `Service` when you need to show the permission's dialog.

**Comment by wahibhaq** [comment]
hmm right. Yeah that workaround is in my mind but thought KPermissions will handle it internally. 

Btw I already tried https://github.com/nabinbhandari/Android-Permissions and it does what I require if I ignore some caveats. Maybe something for you to checkout if you haven't already. 

Thanks again for your response 👍

**Comment by Fondesa** [comment]
Thanks for the advice. I'll check it out.
