### ISSUE TITLE
onAccepted Listener not being called if the permission is granted already

### ISSUE THREAD

**Issue by Chullian** [Fondesa/KPermissions#27]
I am using kPermissions of version 1.0.0 and using DSL for listeners. But the onAccepted is not getting called if the permission is already granted. and is there any way to know if the permission is denied already

**Comment by Fondesa** [comment]
If the permissions are already granted, the method `onAccepted()` should be invoked. Can you post your code in which you can demonstrate that behavior?

**Comment by Chullian** [comment]
` private fun permissionCheck() {
        val request = permissionsBuilder(
            Manifest.permission.READ_EXTERNAL_STORAGE,
            Manifest.permission.WRITE_EXTERNAL_STORAGE
        ).build()
        request.send()

        request.listeners {

            onAccepted { permissions ->
                Log.d("PERMISSION", "accepted")
                observeFiles()
            }

            onDenied { permissions ->
                Log.d("PERMISSION", "denied")
            }

            onPermanentlyDenied { permissions ->
                // Notified when the permissions are permanently denied.
                Log.d("PERMISSION", "permanently denied")

            }

            onShouldShowRationale { permissions, nonce ->
                // Notified when the permissions should show a rationale.
                Log.d("PERMISSION", "Rationale")
            }
        }
    }`

**Comment by Fondesa** [comment]
The problem here is related to the fact you are attaching the listeners after sending the request.
You should attach them before sending the request:
```kotlin
private fun permissionCheck() {
val request = permissionsBuilder(
    Manifest.permission.READ_EXTERNAL_STORAGE,
    Manifest.permission.WRITE_EXTERNAL_STORAGE
).build()
request.listeners { ... }
request.send()
```
