### ISSUE TITLE
shouldShowRationale does not working properly

### ISSUE THREAD

**Issue by TurKurT656** [fondesa/kpermissions#272]
### Description
This is the code that I wrote for handling permission:
```kotlin
request.addListener {
    when {
        it.allGranted() -> onPermissionAccepted()
        it.anyShouldShowRationale() -> showRationaleDialog() { request.send() }
        it.anyPermanentlyDenied() -> showNeverAskAgainDialog()
        it.anyDenied() -> onPermissionDenied?.invoke()
    }
}
```
When I call `request.send()` for the first time and after that I press **Deny** button, inside the listener I get `shouldShowRationale()` as `true` and because of that immediately my  `RationaleDialog` shows up. And even If I dismiss that dialog and call `request.send()` again, instead of getting `anyShouldShowRationale` as `true` (to show `RationaleDialog` before the system permission dialog) it shows the system permission dialog. Is this an expected behavior or am I missing something?

-----------

**KPermissions version**:
3.2.1

**API level**:
All

**Expected Behavior**: 
- User clicks on a button so `request.send()` gets called
- System permission dialog shows up
- If user press on **Deny** button the listener should not give `anyShouldShowRationale()` as `true` and it must return `anyDenied()` as `true`
- After user presses the same button again, We call `request.send()` again
- This time before system permission dialog. the listener must return `anyShouldShowRationale()` as `true` so that we can show rationale dialog and after user clicks on `OK` button inside that dialog we have to show system dialog.

**Comment by fondesa** [comment]
This is the expected Android behavior.

To be more precise:
> If user press on Deny button the listener should not give anyShouldShowRationale() as true and it must return anyDenied() as true

When `anyShouldShowRationale` is `true` it means that `anyDenied` is `true`, but, if `anyDenied` is `true`, it does not mean necessarily that `anyShouldShowRationale` is `true`.

To be clearer: the only case in which `anyDenied` is `true` and `anyShouldShowRationale` is `false` is when a permission is denied permanently (the user clicked on "never ask again").

You can still implement the logic you described doing the checks before sending the permission request (you can use `PermissionRequest.checkStatus()`).

Feel free to re-open the issue if something is unclear.
