### ISSUE TITLE
Does ConcurrentModificationException occur only with my usage or it is common error?

### ISSUE THREAD

**Issue by zhombie** [fondesa/kpermissions#288]
<img width="642" alt="Screenshot 2021-12-18 at 04 08 03" src="https://user-images.githubusercontent.com/26120169/146614067-12404932-9553-4983-8582-bccf57836dc1.png">

I think the problem with removeListener, which triggers BasePermissionRequest#removeListener() method on its parallel usage at RuntimePermissionRequest#onPermissionsResult() forEach {}

<img width="896" alt="Screenshot 2021-12-18 at 04 17 57" src="https://user-images.githubusercontent.com/26120169/146614312-0b80b2bd-81e1-4b8b-9f15-3a92a832f95e.png">

**Comment by fondesa** [comment]
Hi, thanks for your submission.

I have few questions to be able to reproduce this:
1. Are you attaching multiple listeners to the same request?
2. Does it happen consistently or only randomly?
3. Can you share the usage of that API to help me reproducing it?

**Comment by fondesa** [comment]
NVM, I'm fixing this for all the cases: https://github.com/fondesa/kpermissions/pull/289

The fix will be available from the next release
